#!/bin/bash

EXECUTABLE="./main"
SOURCE_DIR="./"  # Directory where your Go source files are located

build_project() {
    echo "Building the project..."
    go build -o $EXECUTABLE $SOURCE_DIR
}

# Check if the executable exists and build if it doesn't
if [ ! -f "$EXECUTABLE" ]; then
    build_project
fi

if [ "$#" -lt 1 ]; then
    echo "Usage: go-forth [build|dev]"
    exit 1
fi

case "$1" in
    build)
        $EXECUTABLE build
        ;;
    dev)
        $EXECUTABLE dev
        ;;
    *)
        echo "Invalid command. Use 'build' or 'dev'."
        exit 1
        ;;
esac
